import { useState, useEffect, useRef } from 'react'
import type {
  grayscale       as GrayscaleFn,
  invert          as InvertFn,
  brightness      as BrightnessFn,
  sepia           as SepiaFn,
  frame_luma_stats as FrameLumaStatsFn,
} from '../wasm-pkg/avi_wasm'

// ── Public API surface exposed by the WASM module ────────────────────────────
export interface WasmApi {
  grayscale:        typeof GrayscaleFn
  invert:           typeof InvertFn
  brightness:       typeof BrightnessFn
  sepia:            typeof SepiaFn
  frame_luma_stats: typeof FrameLumaStatsFn
}

export type WasmStatus = 'loading' | 'ready' | 'error'

interface UseWasmReturn {
  status: WasmStatus
  error:  string | null
  api:    WasmApi | null
}

/**
 * Asynchronously loads and initialises the avi-wasm WebAssembly module.
 * The module is loaded once and cached via ref — safe to call from any component.
 */
export const useWasm = (): UseWasmReturn => {
  const [status, setStatus] = useState<WasmStatus>('loading')
  const [error,  setError]  = useState<string | null>(null)
  const apiRef = useRef<WasmApi | null>(null)

  useEffect(() => {
    let cancelled = false

    ;(async () => {
      try {
        // Dynamic import lets Vite handle the .wasm binary automatically
        const mod = await import('../wasm-pkg/avi_wasm.js')
        // `mod.default` is the async init function generated by wasm-bindgen
        await mod.default()

        if (!cancelled) {
          apiRef.current = mod as unknown as WasmApi
          setStatus('ready')
        }
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : String(e))
          setStatus('error')
        }
      }
    })()

    return () => { cancelled = true }
  }, [])

  return { status, error, api: apiRef.current }
}
